name: Ci

on:
  push:

jobs:

  build_apk:
    runs-on: depot-ubuntu-24.04-64

    steps:
      - uses: actions/checkout@v4

      - run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Mount Gradle user home on tmpfs
        run: |
          sudo mkdir -p /mnt/gradle
          sudo mount -t tmpfs -o size=64g tmpfs /mnt/gradle
          sudo chown -R $USER:$USER /mnt/gradle
          ln -s /mnt/gradle ~/.gradle

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/build.gradle') }}

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: build/app/outputs/flutter-apk/app-release.apk
