name: Ci

on:
  push:

jobs:

  build_apk:
    runs-on: depot-ubuntu-24.04-64

    steps:
      - uses: actions/checkout@v4

      - run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - run: flutter pub get

      - run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: build/app/outputs/flutter-apk/app-release.apk
